In [84]:
import matplotlib.pyplot as plt
import numpy as np

from mpl_toolkits.basemap import Basemap

import xarray as xr
import pandas as pd
import cmocean
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import matplotlib.colors as colors

from mpl_toolkits.axes_grid1 import AxesGrid
from mpl_toolkits.basemap import Basemap

In [155]:

ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/ph_ens_ssp585_biascorrected_mean.nc')
# ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/ph_ens_ssp126_biascorrected_mean.nc')
# ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/ph_ens_ssp245_biascorrected_mean.nc')


ds1 = 10**(-1*ds1)

ds1 = ds1*10**(9)


In [156]:
lat_range = slice(0, 30)  # Latitude range from -30 to 30
lon_range = slice(38, 78)  # Longitude range from 30 to 100

ds1_hist  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('1985', '2014'))#.mean(['lat', 'lon'])
ds1_hist_avg= ds1_hist.mean(['lat', 'lon'])




In [157]:
da = ds1_hist_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended = xt.detrend(
    da,
    dim="time",
    detrend_type="linear"
)

# -----------------------------
# Step 4: Restore NaNs
# -----------------------------
# da_detrended = da_detrended.where(da.notnull())


In [158]:
# da_detrended.mean()

In [159]:
# hist_detrend  = da_detrended.sel(time=slice('1985', '2014'))#.mean(['lat', 'lon'])

threshold= da_detrended.quantile(
    0.95, dim="time", skipna=True
)
threshold

<xarray.DataArray 'ph' ()> Size: 8B
array(0.23913946)
Coordinates:
    quantile  float64 8B 0.95

In [160]:
hotspot_ph = da_detrended.where(da_detrended > threshold, drop=True)

In [161]:
hotspot_ph

<xarray.DataArray 'ph' (time: 18)> Size: 144B
array([0.27244167, 0.24993442, 0.29983296, 0.25891599, 0.27858673,
       0.25910569, 0.27297759, 0.24018418, 0.25401217, 0.26133317,
       0.24530223, 0.24377604, 0.27169343, 0.28079569, 0.26705614,
       0.30330086, 0.29487118, 0.28483081])
Coordinates:
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
  * time      (time) object 144B 1985-08-15 12:00:00 ... 2014-08-15 12:00:00
    lev       float64 8B 500.0
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95

In [162]:
# lat_range = slice(-30, -18)  # Latitude range from -30 to 30
# lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_nf  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('2015', '2040'))#.mean(['lat', 'lon'])
ds1_nf_avg= ds1_nf.mean(['lat', 'lon'])

da_nf = ds1_nf_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended_nf = xt.detrend(
    da_nf,
    dim="time",
    detrend_type="linear"
)
hotspot_ph_nf = da_detrended_nf.where(da_detrended_nf > threshold, drop=True)

hotspot_ph_nf

<xarray.DataArray 'ph' (time: 21)> Size: 168B
array([0.33984685, 0.35050474, 0.34683364, 0.30147658, 0.2742583 ,
       0.24143964, 0.26822899, 0.25016181, 0.24953699, 0.26715873,
       0.26102888, 0.24227851, 0.28096935, 0.25430817, 0.29533768,
       0.30797735, 0.35731536, 0.3376789 , 0.38435905, 0.41421381,
       0.2513177 ])
Coordinates:
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
  * time      (time) object 168B 2015-08-15 12:00:00 ... 2040-09-15 00:00:00
    lev       float64 8B 500.0
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95

In [163]:
# lat_range = slice(-30, -18)  # Latitude range from -30 to 30
# lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_nf  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('2041', '2070'))#.mean(['lat', 'lon'])
ds1_nf_avg= ds1_nf.mean(['lat', 'lon'])

da_nf = ds1_nf_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended_nf = xt.detrend(
    da_nf,
    dim="time",
    detrend_type="linear"
)
hotspot_ph_nf = da_detrended_nf.where(da_detrended_nf > threshold, drop=True)

hotspot_ph_nf

<xarray.DataArray 'ph' (time: 46)> Size: 368B
array([0.28273335, 0.3046807 , 0.2729731 , 0.46865346, 0.32211628,
       0.27941569, 0.2847179 , 0.2594071 , 0.49138932, 0.33013529,
       0.44737799, 0.29988409, 0.24191749, 0.42800091, 0.28293501,
       0.38957273, 0.33921543, 0.32124463, 0.30858643, 0.30407974,
       0.23920234, 0.28773262, 0.31658701, 0.28639124, 0.32317737,
       0.37143233, 0.38373943, 0.26377828, 0.44344376, 0.43384114,
       0.2404919 , 0.30576154, 0.28825412, 0.50147395, 0.31875096,
       0.37216498, 0.33328488, 0.28324695, 0.55464333, 0.35549434,
       0.40836047, 0.42166113, 0.27382878, 0.38346765, 0.65619504,
       0.43819979])
Coordinates:
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
  * time      (time) object 368B 2041-04-15 00:00:00 ... 2070-09-15 00:00:00
    lev       float64 8B 500.0
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95

In [164]:
# lat_range = slice(-30, -18)  # Latitude range from -30 to 30
# lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_nf  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('2071', '2100'))#.mean(['lat', 'lon'])
ds1_nf_avg= ds1_nf.mean(['lat', 'lon'])

da_nf = ds1_nf_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended_nf = xt.detrend(
    da_nf,
    dim="time",
    detrend_type="linear"
)
hotspot_ph_nf = da_detrended_nf.where(da_detrended_nf > threshold, drop=True)

hotspot_ph_nf

<xarray.DataArray 'ph' (time: 62)> Size: 496B
array([0.32244776, 0.30098739, 0.47384036, 0.44201842, 0.32290564,
       0.28023726, 0.47623593, 0.25039354, 0.41452377, 0.37791663,
       0.38414981, 0.29401458, 0.39318964, 0.34051659, 0.4037435 ,
       0.42350879, 0.27724194, 0.3639137 , 0.35831537, 0.38563647,
       0.27773147, 0.25883886, 0.41485163, 0.2862013 , 0.28688142,
       0.42368652, 0.43199283, 0.27221882, 0.25197614, 0.42949331,
       0.43065532, 0.29657237, 0.41166285, 0.44341498, 0.38507653,
       0.33409332, 0.50303185, 0.27226674, 0.49401676, 0.26024518,
       0.45231496, 0.36878882, 0.28356724, 0.53697206, 0.25497477,
       0.36987915, 0.27325344, 0.56322392, 0.4121354 , 0.2852678 ,
       0.55523876, 0.27556952, 0.4915968 , 0.35632071, 0.25908749,
       0.5680855 , 0.42303985, 0.27037668, 0.54392687, 0.37787978,
       0.55042568, 0.2666027 ])
Coordinates:
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
  * time      (time) object 496B 2071-04-15 00:00:00 ... 2100-09-15 00:00:00
    lev       float64 8B 500.0
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95