In [1]:
import matplotlib.pyplot as plt
import numpy as np

from mpl_toolkits.basemap import Basemap

import xarray as xr
import pandas as pd
import cmocean
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import matplotlib.colors as colors

from mpl_toolkits.axes_grid1 import AxesGrid
from mpl_toolkits.basemap import Basemap

In [134]:

# ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/ph_ens_ssp585_biascorrected_mean.nc')
# ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/ph_ens_ssp126_biascorrected_mean.nc')
# ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/ph_ens_ssp245_biascorrected_mean.nc')
ds1 = xr.open_dataset('/media/athira/One Touch/final_datasets/Edited_plots/merged_files/pH_ensemble_ssp126_merged_r1.nc')

ds1 = 10**(-1*ds1)

ds1 = ds1*10**(9)


In [135]:
lat_range = slice(-30, -18)  # Latitude range from -30 to 30
lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_hist  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('1985', '2014'))#.mean(['lat', 'lon'])
ds1_hist_avg= ds1_hist.mean(['lat', 'lon'])




In [136]:
da = ds1_hist_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended = xt.detrend(
    da,
    dim="time",
    detrend_type="linear"
)

# -----------------------------
# Step 4: Restore NaNs
# -----------------------------
# da_detrended = da_detrended.where(da.notnull())


In [137]:
# da_detrended.mean()

In [138]:
# hist_detrend  = da_detrended.sel(time=slice('1985', '2014'))#.mean(['lat', 'lon'])

threshold= da_detrended.quantile(
    0.95, dim="time", skipna=True
)
threshold

<xarray.DataArray 'ph' ()> Size: 8B
array(0.5489487)
Coordinates:
    quantile  float64 8B 0.95

In [139]:
hotspot_ph = da_detrended.where(da_detrended > threshold, drop=True)

In [140]:
hotspot_ph

<xarray.DataArray 'ph' (time: 18)> Size: 144B
array([0.55428364, 0.5836371 , 0.57565861, 0.55031877, 0.55575766,
       0.55169488, 0.57448124, 0.56359247, 0.59064664, 0.6273402 ,
       0.55980086, 0.55625048, 0.59026064, 0.5499619 , 0.57465488,
       0.61934651, 0.60951449, 0.54922244])
Coordinates:
  * time      (time) object 144B 1987-02-14 00:00:00 ... 2014-03-15 12:00:00
    lev       float64 8B 500.0
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95

In [141]:
# lat_range = slice(-30, -18)  # Latitude range from -30 to 30
# lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_nf  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('2015', '2040'))#.mean(['lat', 'lon'])
ds1_nf_avg= ds1_nf.mean(['lat', 'lon'])

da_nf = ds1_nf_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended_nf = xt.detrend(
    da_nf,
    dim="time",
    detrend_type="linear"
)
hotspot_ph_nf = da_detrended_nf.where(da_detrended_nf > threshold, drop=True)

hotspot_ph_nf

<xarray.DataArray 'ph' (time: 49)> Size: 392B
array([0.57003937, 0.56390072, 0.5932957 , 0.56377041, 0.55017899,
       0.60414055, 0.58977799, 0.65290821, 0.60174577, 0.61898786,
       0.6505065 , 0.57452026, 0.58022959, 0.68431297, 0.6063194 ,
       0.58611448, 0.55211848, 0.6511736 , 0.57883731, 0.61087922,
       0.68333455, 0.60891247, 0.63043719, 0.69058162, 0.62992879,
       0.61842738, 0.56035063, 0.65924245, 0.59648021, 0.62822489,
       0.69393026, 0.5984327 , 0.57340609, 0.66162513, 0.58970586,
       0.59048969, 0.68999419, 0.59864037, 0.64902966, 0.59195176,
       0.57908987, 0.65351183, 0.60302318, 0.61804175, 0.70768101,
       0.62349075, 0.60447359, 0.67149067, 0.5754065 ])
Coordinates:
  * time      (time) object 392B 2015-02-14 00:00:00 ... 2039-03-15 12:00:00
    lev       float64 8B 500.0
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95

In [142]:
# lat_range = slice(-30, -18)  # Latitude range from -30 to 30
# lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_nf  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('2041', '2070'))#.mean(['lat', 'lon'])
ds1_nf_avg= ds1_nf.mean(['lat', 'lon'])

da_nf = ds1_nf_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended_nf = xt.detrend(
    da_nf,
    dim="time",
    detrend_type="linear"
)
hotspot_ph_nf = da_detrended_nf.where(da_detrended_nf > threshold, drop=True)

hotspot_ph_nf

<xarray.DataArray 'ph' (time: 77)> Size: 616B
array([0.6147923 , 0.56271352, 0.56481104, 0.65445169, 0.60138299,
       0.6060206 , 0.58159769, 0.64177992, 0.56665286, 0.58490734,
       0.64813235, 0.5646524 , 0.57872103, 0.67838662, 0.60394499,
       0.69915718, 0.72279164, 0.62731034, 0.57036713, 0.65480963,
       0.58581923, 0.63904291, 0.68115431, 0.59750571, 0.64214246,
       0.66348804, 0.55053725, 0.65351595, 0.6820472 , 0.59718301,
       0.6216123 , 0.67223206, 0.57256443, 0.66540251, 0.57615164,
       0.64165825, 0.73588058, 0.6171925 , 0.59626107, 0.72095357,
       0.60219483, 0.6615127 , 0.7509936 , 0.65586733, 0.69259078,
       0.73956813, 0.65512912, 0.67366577, 0.71918961, 0.61284965,
       0.63535895, 0.66324993, 0.55698938, 0.57103097, 0.65555628,
       0.57209394, 0.64477393, 0.6756674 , 0.59009554, 0.66318363,
       0.76628765, 0.68156719, 0.60069542, 0.6818482 , 0.58923652,
       0.57384956, 0.63969282, 0.57517449, 0.58782137, 0.64352298,
       0.58843799, 0.63287236, 0.56693704, 0.57156728, 0.66057844,
       0.59232006, 0.6226652 ])
Coordinates:
  * time      (time) object 616B 2041-02-14 00:00:00 ... 2070-02-14 00:00:00
    lev       float64 8B 500.0
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95

In [143]:
# lat_range = slice(-30, -18)  # Latitude range from -30 to 30
# lon_range = slice(30, 120)  # Longitude range from 30 to 100

ds1_nf  = ds1.sel(lat=lat_range, lon=lon_range, time=slice('2071', '2100'))#.mean(['lat', 'lon'])
ds1_nf_avg= ds1_nf.mean(['lat', 'lon'])

da_nf = ds1_nf_avg['ph']   # assuming your DataArray is called `ph`
import xrft as xt
# Create numeric time axis
da_detrended_nf = xt.detrend(
    da_nf,
    dim="time",
    detrend_type="linear"
)
hotspot_ph_nf = da_detrended_nf.where(da_detrended_nf > threshold, drop=True)

hotspot_ph_nf

<xarray.DataArray 'ph' (time: 76)> Size: 608B
array([0.57697264, 0.64452892, 0.56157812, 0.56786421, 0.64392321,
       0.57221373, 0.58315803, 0.62547259, 0.60660574, 0.60218817,
       0.62544119, 0.59860552, 0.69319674, 0.56727008, 0.57189907,
       0.65475716, 0.58173546, 0.64178888, 0.65791588, 0.58129985,
       0.62247512, 0.65209374, 0.55788796, 0.57164925, 0.60578639,
       0.6103414 , 0.6462044 , 0.59079159, 0.64061638, 0.70856909,
       0.58769404, 0.60659799, 0.65730149, 0.61284989, 0.58616451,
       0.65606079, 0.57026903, 0.61945366, 0.74110057, 0.59892376,
       0.60503435, 0.68948682, 0.5900811 , 0.57329289, 0.62960038,
       0.60182127, 0.65406521, 0.56863036, 0.62411309, 0.69125884,
       0.59247631, 0.59762484, 0.68764269, 0.62080008, 0.61403719,
       0.67061812, 0.56616672, 0.60020274, 0.64570868, 0.69278473,
       0.59488919, 0.57678305, 0.65230891, 0.55986605, 0.61938983,
       0.62139329, 0.56659428, 0.6049478 , 0.64751579, 0.55001617,
       0.59172193, 0.66695119, 0.58612733, 0.61635683, 0.67686514,
       0.57192104])
Coordinates:
  * time      (time) object 608B 2071-02-14 00:00:00 ... 2100-03-15 12:00:00
    lev       float64 8B 500.0
    DEPTH1_1  float32 4B 0.0
    TIME      datetime64[ns] 8B 2017-01-01
    olevel    float32 4B 0.5058
    quantile  float64 8B 0.95